version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "albanlove"
      MYSQL_DATABASE: "eventalia_beta"
      MYSQL_USER: "albanlove"
      MYSQL_PASSWORD: "albanlove"
    volumes:
      - db_data:/var/lib/mysql
      - ./eventalia_beta.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
